# Generated by Django 3.0.8 on 2020-08-11 17:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('charity_donation', '0002_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quantity',
            new_name='Donation',
        ),
    ]
